config/routes.rb
Rails.application.routes.draw do

	devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'videos#index'

  resources :videos do
  	collection do
  		get "search" => 'videos#search'
  	end
  end

  resources :my_lists, only: [:index, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/my_list.rb
class MyList < ApplicationRecord

	belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :login
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  has_many :my_lists, dependent: :destroy

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(name) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:name) || conditions.has_key?(:email)
      where(conditions.to_hash).first
    end
  end


  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  def validate_username
    if User.where(email: name).exists?
      errors.add(:name, :invalid)
    end
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      added_attrs = [ :name, :email, :password, :password_confirmation, :remember_me ]
    	devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end



end

app/controllers/my_lists_controller.rb
class MyListsController < ApplicationController

	def create
		v_id = params[:format]
		@my_list = current_user.my_lists.new(video_id: v_id)
		@my_list.save
	end

	def destroy
		v_id = params[:id]
		@my_list = current_user.my_lists.find_by(video_id: v_id)
		@my_list.destroy
	end

	def index
		@my_lists = current_user.my_lists.all.page(params[:page]).per(8).reverse_order
	end

	private
	def my_list_params
		parmas.require(:my_list).permit(
			:video_id, :user_id)
	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    get_data("live" || "ライブ") #検索条件設定
    @movies_page = Kaminari.paginate_array(@movies).page(params[:page]).per(8)
    @my_lists = current_user.my_lists
  end

  def search
    if params[:search].blank?
       get_data("live" || "ライブ")
    else
      get_data("live" + params[:search] || "ライブ" + params[:search])#2つの検索条件でキーワード検索
    end
    @movies_page = Kaminari.paginate_array(@movies).page(params[:page]).per(8)
    @my_lists = current_user.my_lists
    render :index
  end


  def get_data(keyword)
    require 'google/apis/youtube_v3'
    # require 'trollop'
    # opts = Trollop::options do
    #   opt :q, 'Search term', :default => keyword
    #   opt :max_results, 'Max results', :default => 50 #APIのMAX件数取得
    #   opt :order, 'order', :default => 'date' #新着順で取得
    #   opt :regionCode, 'region', :default => 'JP' #第一言語を日本語で取得
    #   opt :type, 'type', :default => 'video'
    #   opt :video_category_id, 'video category id', :default => '10' #音楽カテゴリで取得
    #   # opt :video_definition, 'video definition', :default => 'high' #HD動画のみ取得
    # end


    youtube = Google::Apis::YoutubeV3::YouTubeService.new
    if Rails.env.production?
      youtube.key = Rails.application.secrets.youtube_key
    else
      youtube.key = 'AIzaSyAUat8tsl5tjcPzcsvxs8l3hTW0_203zy0'
    end

    # search_response = youtube.list_searches("id",
    #   q: opts[:q],
    #   max_results: opts[:max_results],
    #   order: opts[:order],
    #   region_code: opts[:regionCode],
    #   type: opts[:type],
    #   video_category_id: opts[:video_category_id]
    #   )

    search_response = youtube.list_searches("id",
      q: keyword,
      max_results: 48,
      order: "date",
      region_code: "JP",
      type: "video",
      video_category_id: "10"
      )

    @movies = search_response.items #Jsonの中身が多かったので必要な情報のみ受けれるようにしています。
    # @movies = []
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_lists_helper.rb
module MyListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
<html lang="ja">
	<title>Livenow</title>
	<%= csrf_meta_tags %>
	<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.0.10/font-awesome-animation.css" type="text/css" media="all" />
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<meta name="description" content="音楽ライブ動画を検索して視聴できる動画サイトです">
	<meta name="keywords" content="ライブナウ,動画,ライブ,バンド,ユーチューブ,livenow,youtube,live,video,movie,music,band,">
	<%= favicon_link_tag %>
</head>

<body>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<%= yield %>
</body>
</html>

app/views/my_lists/_favorites_create.html.erb
<%= link_to my_list_path(@my_list.video_id), remote: true, method: :delete do %>
  <i id="favorite-heart<%= @my_list.video_id %>" class="fas fa-heart faa-ring animated-hover z-depth-5" style="color: red;"></i>
<% end %>

app/views/my_lists/_favorites_delete.html.erb
<%= link_to my_lists_path(@my_list.video_id), remote: true, method: :post do %>
  <i id="favorite-heart<%= @my_list.video_id %>" class="far fa-heart faa-wrench animated-hover z-depth-5" style="color: red;"></i>
<% end %>

app/views/my_lists/create.js.erb
$( ('#favorite-heart<%= @my_list.video_id %>' ) ).html('<%= j( render( 'favorites_create' ) ) %>');

app/views/my_lists/destroy.js.erb
$( ('#favorite-heart<%= @my_list.video_id %>' ) ).html('<%= j( render( 'favorites_delete' ) ) %>');

app/views/my_lists/index.html.erb
<body>
	<div class="container">
		<!-- 操作覧 -->
		<div id="searchbox" class="draggable center hoverable">
			<!-- ヘッダー覧 -->
			<div class="flow-text">
				<%= link_to " top", root_path, class: "fa fa-video-camera icon"%>
				<%= link_to " mypage", my_lists_path, class: "fa fa-user icon"%>
				<%= link_to " logout", destroy_user_session_path, class: "fa fa-sign-out icon", method: :delete %>
			</div><!-- end ヘッダー覧 -->
				<!-- 検索覧 -->
				<%= form_tag search_videos_path, :method => 'get' , :style => "display: flex;"  do %>
					<%= text_field_tag :search, params[:search], :placeholder => "曲名、アーティスト名は正確に入力してください", :class => "input-field", :style => "height: 2.5rem; font-size: 90%;" %>
					<%= button_tag :type => "submit", :name => nil , :class => "btn waves-effect", :style => "height: 2.5rem;" do %>
						<i class="fa fa-search faa-vertical animated-hover"></i>
					<% end %>
				<% end %><!-- end 検索覧 -->
			<!-- フッター覧 -->
			<div class="page">
				<%= paginate @my_lists %>
			</div><!-- end フッター覧 -->
		</div><!-- end 操作覧 -->
		<!-- video覧 -->
		<% @my_lists.each do |movie| %>
			<div id="drag" class="draggable hoverable">
				<% if @my_lists.any?{|m| m.video_id == movie.video_id } %>
					<!-- mylist登録時表示 -->
					<%= link_to my_list_path(movie.video_id), remote: true, method: :delete, id: "favorite-heart#{movie.video_id}" do %>
						<i class="fas fa-heart faa-ring animated-hover z-depth-5" style="color: red;"></i>
					<% end %><!-- end mylist登録時表示 -->
				<% else %>
					<!-- mylist未登録時表示 -->
					<%= link_to my_lists_path(movie.video_id), remote: true, method: :post, id: "favorite-heart#{movie.video_id}" do %>
						<i class="far fa-heart faa-wrench animated-hover z-depth-5" style="color: red;"></i>
					<% end %><!--end mylist未登録時表示 -->
				<% end %>
				<!-- youtubeAPI覧 -->
				<%= content_tag(:iframe, '', src: "https://www.youtube.com/embed/#{movie.video_id}", width: "90%", height: "100%", frameborder: 0, allowfullscreen:true) %>
			</div>
		<% end %><!-- end video覧 -->
	</div>
</body>

app/views/videos/index.html.erb
<body>
	<div class="container">
		<!-- 操作覧 -->
		<div id="searchbox" class="draggable center hoverable">
			<!-- ヘッダー覧 -->
			<div class="flow-text">
				<%= link_to " top", root_path, class: "fa fa-video-camera icon"%>
				<%= link_to " mypage", my_lists_path, class: "fa fa-user icon"%>
				<%= link_to " logout", destroy_user_session_path, class: "fa fa-sign-out icon", method: :delete %>
			</div><!-- end ヘッダー覧 -->
				<!-- 検索覧 -->
				<%= form_tag search_videos_path, :method => 'get' , :style => "display: flex;"  do %>
					<%= text_field_tag :search, params[:search], :placeholder => "曲名、アーティスト名は正確に入力してください", :class => "input-field", :style => "height: 2.5rem; font-size: 90%;" %>
					<%= button_tag :type => "submit", :name => nil , :class => "btn waves-effect", :style => "height: 2.5rem;" do %>
						<i class="fa fa-search faa-vertical animated-hover"></i>
					<% end %>
				<% end %><!-- end 検索覧 -->
			<!-- フッター覧 -->
			<div class="page">
				<%= paginate @movies_page %>
			</div><!-- end フッター覧 -->
		</div><!-- end 操作覧 -->
		<!-- video覧 -->
		<% @movies_page.each do |movie| %>
			<div id="drag" class="draggable hoverable">
				<% if @my_lists.any?{|m| m.video_id == movie.id.video_id } %>
					<!-- mylist登録時表示 -->
					<%= link_to my_list_path(movie.id.video_id), remote: true, method: :delete, id: "favorite-heart#{movie.id.video_id}" do %>
						<i class="fas fa-heart faa-ring animated-hover z-depth-5" style="color: red;"></i>
					<% end %><!-- end mylist登録時表示 -->
				<% else %>
					<!-- mylist未登録時表示 -->
					<%= link_to my_lists_path(movie.id.video_id), remote: true, method: :post, id: "favorite-heart#{movie.id.video_id}" do %>
						<i class="far fa-heart faa-wrench animated-hover z-depth-5" style="color: red;"></i>
					<% end %><!--end mylist未登録時表示 -->
				<% end %>
				<!-- youtubeAPI覧 -->
				<%= content_tag(:iframe, '', src: "https://www.youtube.com/embed/#{movie.id.video_id}", width: "90%", height: "100%", frameborder: 0, allowfullscreen:true) %>
			</div>
		<% end %><!-- end video覧 -->
	</div>
</body>